futhor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib import auth

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^nova/', include('nova.urls')),
]

nova/urls.py
# -*- coding:utf-8 -*-
__author__ = 'qiuyyb'

from django.conf.urls import url

from . import views
urlpatterns = [
    url(r'^$', views.console, name='index'),
    url(r'^home/$', views.home, name='home'),
    url(r'^login/$', views.Login, name='login'),
    url(r'^logout/$', views.Logout, name='logout'),
    url(r'^console/$', views.console, name='console'),
    url(r'^config_ssh_public_key/$', views.config_ssh_public_key, name='config_ssh_public_key'),
    url(r'^asset/$', views.asset, name='asset'),
    url(r'^asset/asset_group$', views.asset_group, name='asset_group'),
    url(r'^download/$', views.download, name='download'),
    url(r'^fpcy_stat/$', views.fpcy_stat, name='fpcy_stat'),
    url(r'^ecai_stat/$', views.ecai_stat, name='ecai_stat'),
    url(r'^get_user_asset/$', views.get_user_asset, name='get_user_asset'),
    url(r'^get_asset/$', views.get_asset, name='get_asset'),
    url(r'^asset/add/$', views.asset_add, name='asset_add'),
    url(r'^asset/(?P<asset_id>[0-9]+)/change/$', views.asset_change, name='asset_change'),
    url(r'^asset/(?P<asset_id>[0-9]+)/delete/$', views.asset_delete, name='asset_delete'),
    url(r'^host_connect/(?P<asset_id>[0-9]+)/$', views.host_connect, name='host_connect'),
    url(r'^get_auth_obj/$', views.get_auth_obj, name='get_auth_obj'),
    url(r'^get_free_asset/$', views.get_free_asset, name='get_free_asset'),
    url(r'^get_database/$', views.get_database, name='get_database'),
    url(r'^get_max_port/$', views.get_max_port, name='get_max_port'),
    url(r'^get_new_line/$', views.get_new_line, name='get_new_line'),
    url(r'^get_fpcy_qyjkqy_detail/$', views.get_fpcy_qyjkqy_detail, name='get_fpcy_qyjkqy_detail'),
    url(r'^app/deploy/$', views.app_deploy, name='apps_deploy'),
    url(r'^app/$', views.apps, name='apps_list'),
    url(r'^log/access_log/$', views.access_log, name='access_log'),
    url(r'^app/start/$', views.start_app, name='start_app'),
    url(r'^app/stop/$', views.stop_app, name='stop_app'),
    url(r'^app/reload/$', views.reload_app, name='reload_app'),
    url(r'^app/rollback_app/$', views.rollback_app, name='rollback_app'),
    url(r'^app/update/$', views.update_app, name='update_app'),
    url(r'^app/config_file/$', views.config_file, name='config_file'),
    url(r'^app/config_file/add/$', views.config_file_add, name='config_file_add'),
    # url(r'^app/config_file/(?P<app_name>[\w\-]+)/(?P<env>[\w]+)/(?P<file_path>.+)/(?P<file_name>.+)/editor/$',
    #     views.config_file_editor, name='config_file_editor'),
    url(r'^app/config_file/editor/(?P<app_name>[\w\-]+)/(?P<env>[\w]+)/(?P<file_path>.+)/$',
        views.config_file_editor, name='config_file_editor'),
    url(r'^app/save_config_file/$', views.save_config_file, name='save_config_file'),
    url(r'^help/$', views.help, name='help'),
    url(r'^http_data/$', views.http_data, name='http_data'),
    url(r'^message/$', views.message, name='message'),
    url(r'^monitor/web$', views.monitor_web, name='monitor_web'),
    url(r'^monitor/fpcy_request_log/$', views.fpcy_request_log, name='fpcy_request_log'),
    url(r'^monitor/fpcy_request_area/$', views.fpcy_request_area, name='fpcy_request_area'),
    url(r'^monitor/get_fpcy_request_area/$', views.get_fpcy_request_area, name='get_fpcy_request_area'),
    url(r'^upload/$', views.upload_file, name='upload'),
    url(r'^upload/file/$', views.upload_file_list, name='upload_file_list'),
    url(r'^upload/ksbm_oss_file/$', views.update_ksbm_oss_file, name='ksbm_oss_file'),
    url(r'^task/$', views.task_list, name='task_list'),
    url(r'^task/log/$', views.task_log, name='task_log'),
    url(r'^task/status/$', views.get_task_status, name='get_task_status'),
    url(r'^deny/$', views.deny, name='deny'),
    url(r'^sql_submit/$', views.sql_submit, name='sql_submit'),
    url(r'^sql_list/$', views.sql_list, name='sql_list'),
    url(r'^sql_exec/$', views.sql_exec, name='sql_exec'),
    url(r'^shell/$', views.shell, name='shell'),
    url(r'^view/$', views.view, name='view'),
    url(r'^ecctaaDeploy$', views.ecctaaDeploy, name='ecctaaDeploy'),
]

nova/models.py
# -*- coding:utf-8 -*-

from django.db import models
from django.contrib.auth.models import User, Group
import hashlib
import os
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_v1_5 as Cipher_PKCS1_v1_5
import base64
import time

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
rsa_pub = os.path.join(BASE_DIR, 'script', 'rsa.pub')
rsa_key = os.path.join(BASE_DIR, 'script', 'rsa.key')


def _enc_(data=''):
    with open(rsa_pub, 'r') as f:
        public_key = f.read()
        rsa_key_obj = RSA.importKey(public_key)
        cipher_obj = Cipher_PKCS1_v1_5.new(rsa_key_obj)
        cipher_text = base64.b64encode(cipher_obj.encrypt(data))
        return cipher_text

# Create your models here.
# 定义所属的环境
ENV = (
    ('product', U'生产环境'),
    ('staging', U'准生产环境'),
    ('uat', U'用户测试环境'),
    ('test', U'测试环境'),
    ('dev', U'开发环境')
)

ASSET_STATUS = (
    (1, u"已使用"),
    (2, u"未使用"),
    (3, u"报废")
)

ASSET_TYPE = (
    (1, u"物理机"),
    (2, u"虚拟机"),
    (3, u"交换机"),
    (4, u"路由器"),
    (5, u"防火墙"),
    (6, u"Docker"),
    (7, u"其他")
)

ASSET_CONNECT_METHOD = (
    ('Password', u"密码连接"),
    ('PublicKey', u"公钥连接")
)


class AssetGroup(models.Model):
    name = models.CharField(max_length=80, unique=True, verbose_name=u"主机组名称")
    comment = models.CharField(max_length=160, blank=True, null=True, verbose_name=u"备注")
    user_groups = models.ManyToManyField(Group, blank=True, verbose_name=u"所属用户组")

    def __unicode__(self):
        return self.name


class Asset(models.Model):
    """
    主机
    """
    ip = models.CharField(unique=True, max_length=32, blank=True, null=True, verbose_name=u"主机IP")
    other_ip = models.CharField(max_length=255, blank=True, null=True, verbose_name=u"其他IP")
    hostname = models.CharField(max_length=50, verbose_name=u"主机名")
    port = models.IntegerField(blank=True, null=True, verbose_name=u"端口号")
    asset_groups = models.ManyToManyField(AssetGroup, blank=True, verbose_name=u"所属主机组")
    username = models.CharField(max_length=16, blank=True, null=True, verbose_name=u"管理用户名")
    password = models.CharField(max_length=256, blank=True, null=True, verbose_name=u"密码")
    connect_method = models.CharField(choices=ASSET_CONNECT_METHOD, max_length=30, verbose_name=u'连接方式')
    public_key_file = models.CharField(max_length=512, blank=True, null=True, verbose_name=u"私钥文件")
    use_default_auth = models.BooleanField(default=True, verbose_name=u"使用默认管理账号")
    mac = models.CharField(max_length=20, blank=True, null=True, verbose_name=u"MAC地址")
    remote_ip = models.CharField(max_length=16, blank=True, null=True, verbose_name=u'远控卡IP')
    brand = models.CharField(max_length=64, blank=True, null=True, verbose_name=u'硬件厂商型号')
    cpu = models.CharField(max_length=64, blank=True, null=True, verbose_name=u'CPU')
    memory = models.CharField(max_length=128, blank=True, null=True, verbose_name=u'内存')
    disk = models.CharField(max_length=1024, blank=True, null=True, verbose_name=u'硬盘')
    system_type = models.CharField(max_length=32, blank=True, null=True, verbose_name=u"系统类型")
    system_version = models.CharField(max_length=8, blank=True, null=True, verbose_name=u"系统版本号")
    system_arch = models.CharField(max_length=16, blank=True, null=True, verbose_name=u"系统平台")
    cabinet = models.CharField(max_length=32, blank=True, null=True, verbose_name=u'机柜号')
    position = models.IntegerField(blank=True, null=True, verbose_name=u'机器位置')
    number = models.CharField(max_length=32, blank=True, null=True, verbose_name=u'资产编号')
    status = models.IntegerField(choices=ASSET_STATUS, blank=True, null=True, default=1, verbose_name=u"机器状态")
    asset_type = models.IntegerField(choices=ASSET_TYPE, blank=True, null=True, verbose_name=u"主机类型")
    env = models.CharField(choices=ENV, max_length=25, blank=True, null=True, verbose_name=u"运行环境")
    sn = models.CharField(max_length=128, blank=True, null=True, verbose_name=u"SN编号")
    date_added = models.DateTimeField(auto_now=True, null=True, verbose_name=u"添加时间")
    is_active = models.BooleanField(default=True, verbose_name=u"是否激活")
    comment = models.CharField(max_length=300, blank=True, null=True, verbose_name=u"备注")
    configs = models.CharField(max_length=128, blank=True, null=True, verbose_name=u"部署的应用")

    def __unicode__(self):
        return self.ip


class AppHost(models.Model):
    ip = models.CharField(max_length=25, blank=False, null=False, verbose_name=u"主机IP")
    name = models.CharField(max_length=40, blank=False, null=False, verbose_name=u"应用名称")
    port = models.IntegerField(blank=False, null=False, verbose_name=u"应用端口号")
    status = models.CharField(max_length=20, blank=False, null=False, verbose_name=u"运行状态")
    deploy_path = models.CharField(max_length=100, blank=True, null=True, verbose_name=u"部署路径")
    comment = models.CharField(max_length=100, blank=True, null=True, verbose_name=u"备注")
    env = models.CharField(max_length=25, blank=False, null=False, verbose_name=u"部署环境")

    def __unicode__(self):
        return '%s:%s' % (self.env, self.name)


class AppGroup(models.Model):
    name = models.CharField(max_length=40, unique=True, verbose_name=u"应用组名称")
    comment = models.CharField(max_length=160, blank=True, null=True, verbose_name=u"备注")
    user_groups = models.ManyToManyField(Group, blank=True, verbose_name=u"所属用户组")

    def __unicode__(self):
        return self.name


class App(models.Model):
    name = models.CharField(max_length=40, blank=False, null=False, verbose_name=u"应用名称")
    port = models.IntegerField(blank=False, null=False, verbose_name=u"应用端口号")
    app_hosts = models.ManyToManyField(AppHost, blank=True, verbose_name=u"应用部署的服务器")
    status = models.CharField(max_length=20, blank=False, null=False, verbose_name=u"运行状态")
    comment = models.CharField(max_length=100, blank=True, null=True, verbose_name=u"备注")
    svn_url = models.TextField(blank=True, null=True, verbose_name=u'SVN路径')
    env = models.CharField(max_length=25, blank=False, null=False, verbose_name=u"部署环境")
    app_groups = models.ManyToManyField(AppGroup, blank=True, verbose_name=u"所属应用组")

    def __unicode__(self):
        return '%s:%s' % (self.env, self.name)


class Task(models.Model):
    task_id = models.CharField(max_length=255, blank=False, null=False, verbose_name=u"任务id")
    name = models.CharField(max_length=80, blank=False, null=False, verbose_name=u"任务名称")
    status = models.CharField(max_length=40, blank=False, null=False, verbose_name=u"运行状态")
    start_time = models.DateTimeField(blank=False, null=False, verbose_name=u"开始时间")
    end_time = models.DateTimeField(blank=True, null=True, verbose_name=u"结束时间")
    result = models.CharField(max_length=1000, blank=True, null=True, verbose_name=u"结果")
    app_id = models.CharField(max_length=30, blank=True, null=True, verbose_name=u"app_id")
    svn_url = models.TextField(blank=True, null=True, verbose_name=u'SVN路径')
    detail = models.CharField(max_length=200, blank=True, null=True, verbose_name=u"任务详情")
    execute_user = models.CharField(max_length=30, blank=True, null=True, verbose_name=u"操作人")

    def __unicode__(self):
        return self.task_id


class AppConfig(models.Model):
    name = models.CharField(max_length=30, blank=False, null=False, verbose_name=u"服务名称")
    svn_url = models.CharField(max_length=200, null=True, verbose_name=u'SVN路径')
    files = models.CharField(max_length=300, blank=False, null=False, verbose_name=u"配置文件")
    env = models.CharField(max_length=25, blank=False, null=False, verbose_name=u"部署环境")

    def __unicode__(self):
        return '%s:%s %s' % (self.env, self.name, self.files)


class Sql(models.Model):
    db_name = models.CharField(max_length=30, blank=False, null=False, verbose_name=u"数据库")
    env = models.CharField(max_length=20, blank=False, null=False, verbose_name=u"环境")
    sql = models.TextField(blank=True, null=True, verbose_name=u"sql")
    start_time = models.DateTimeField(blank=False, null=False, verbose_name=u"开始时间")
    end_time = models.DateTimeField(blank=True, null=True, verbose_name=u"结束时间")
    result = models.CharField(max_length=2000, blank=True, null=True, verbose_name=u"结果")
    submit_user = models.CharField(max_length=30, blank=True, null=True, verbose_name=u"提交人")
    execute_user = models.CharField(max_length=30, blank=True, null=True, verbose_name=u"操作人")
    recovery_file = models.CharField(max_length=80, blank=True, null=True, verbose_name=u"恢复文件")

    def __unicode__(self):
        return '%s:%s' % (self.env, self.db_name)


class Database(models.Model):
    env = models.CharField(max_length=20, blank=False, null=False, verbose_name=u"环境")
    type = models.CharField(max_length=20, blank=False, null=False, verbose_name=u"数据库类型")
    ip = models.CharField(max_length=80, blank=False, null=False, verbose_name=u"ip")
    port = models.CharField(max_length=20, blank=False, null=False, verbose_name=u"端口")
    db_name = models.CharField(max_length=30, blank=False, null=False, verbose_name=u"数据库名称")
    username = models.CharField(max_length=30, blank=False, null=False, verbose_name=u"用户名")
    password = models.CharField(max_length=40, blank=False, null=False, verbose_name=u"密码")
    comment = models.CharField(max_length=40, blank=True, null=True, verbose_name=u"说明")

    def __unicode__(self):
        return '%s:%s' % (self.env, self.db_name)


class UploadFile(models.Model):
    file_name = models.CharField(max_length=30, blank=False, null=False, verbose_name=u"文件名称")
    file_type = models.CharField(max_length=30, blank=True, null=True, verbose_name=u"文件类型")
    file_path = models.CharField(max_length=200, blank=True, null=True, verbose_name=u"文件路径")
    env = models.CharField(max_length=20, blank=False, null=False, verbose_name=u"环境")
    app_name = models.CharField(max_length=64, blank=False, null=False, verbose_name=u"应用名称")
    upload_time = models.DateTimeField(blank=False, null=False, verbose_name=u"上传时间")

nova/forms.py
# -*- coding:utf-8 -*-
__author__ = 'qiuyyb'

from django import forms
from models import Asset, AssetGroup, Task, AppConfig


class UserForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password', max_length=100)


class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()


class AssetForm(forms.ModelForm):
    class Meta:
        model = Asset
        fields = [
            "ip", "other_ip", "hostname", "port", "asset_groups", "username", "password", "configs", "use_default_auth",
            "mac", "remote_ip", "brand", "cpu", "memory", "disk", "system_type", "system_version",
            "cabinet", "position", "number", "status", "asset_type", "env", "sn", "is_active", "comment",
            "system_arch"
        ]


class AssetGroupForm(forms.ModelForm):
    class Meta:
        model = AssetGroup
        fields = [
            "name", "comment"
        ]


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            "task_id", "name", "status", "start_time", "end_time", "result"
        ]


class AppConfigForm(forms.Form):
    name = forms.CharField(label='name', max_length=30)
    svn_url = forms.CharField(label='svn_url', max_length=200)
    files = forms.FileField()
    env = forms.CharField(label='env', max_length=25)
    # class Meta:
    #     model = AppConfig
    #     fields = [
    #         "name", "svn_url", "files", "env"
    #     ]

nova/templates/asset_add.html
{% extends 'base.html' %}
{% block title %}添加主机{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-6 col-sm-8 col-md-12">
                <div class="col-md-offset-1 console-instance-head clearfix">
                    <div class="pull-left">
                        <h3><span>服务器添加</span></h3>
                    </div>
                </div>
                <form class="col-md-offset-1 margin-top-1 form-horizontal asset-add" action="{% url 'asset_add' %}"
                      method="post">
                    {% csrf_token %}
                    {#                        {{ form.as_p }}#}
                    <table>
                        {% for field in form %}
                            <div class="form-group">
                                <label class="col-sm-2 control-label">{{ field.label }}：</label>
                                <div class="col-sm-4 row">
                                    {{ field }}
                                </div>
                            </div>

                        {% endfor %}
                    </table>

                    <div class="form-group">
                        <label class="col-sm-2 control-label"></label>
                        <div class="col-sm-4 row ">
                            <button class="btn btn-primary">保存
                            </button>
                        </div>
                    </div>
                </form>
                {#                <form class="asset-add" action="{% url 'asset_add' %}" method="post">#}
                {#            {% csrf_token %}#}
                {#            <fieldset class="module aligned">#}
                {#                <legend>服务器添加</legend>#}
                {#                <div class="form-row">#}
                {#                    <div>#}
                {#                        <label>服务器 IP:</label>#}
                {#                        <input class="vTextField" name="ip" type="text"/>#}
                {#                    </div>#}
                {#                </div>#}
                {#                <div class="form-row">#}
                {#                    <div>#}
                {#                        <label>主机名称:</label>#}
                {#                        <input class="vTextField" name="hostname" type="text"/>#}
                {#                    </div>#}
                {#                </div>#}
                {#                <div class="form-row">#}
                {#                    <div>#}
                {#                        <label>主机登录名:</label>#}
                {#                        <input class="vTextField" name="username" type="text"/>#}
                {#                    </div>#}
                {#                </div>#}
                {#                <div class="form-row">#}
                {#                    <div>#}
                {#                        <label>主机端口:</label>#}
                {#                        <input class="vTextField" name="port" type="text"/>#}
                {#                    </div>#}
                {#                </div>#}
                {#                <div class="form-row">#}
                {#                    <div>#}
                {#                        <label>密码:</label>#}
                {#                        <input class="vTextField" name="password" type="text"/>#}
                {#                    </div>#}
                {#                </div>#}
                {#                <div class="form-row">#}
                {#                    <div>#}
                {#                        <label>所属主机组:</label>#}
                {#                        {{ form.asset_groups }}#}
                {#                    </div>#}
                {#                </div>#}
                {#                <div class="form-row">#}
                {#                    <div>#}
                {#                        <label>主机类型:</label>#}
                {#                        {{ form.asset_type }}#}
                {#                    </div>#}
                {#                </div>#}
                {#                <div class="form-row">#}
                {#                    <div>#}
                {#                        <label>运行环境:</label>#}
                {#                        {{ form.env }}#}
                {#                    </div>#}
                {#                </div>#}
                {#                <div class="form-row">#}
                {#                    <div>#}
                {#                        <label>部署的应用:</label>#}
                {#                        <input class="vTextField" name="configs" type="text"/>#}
                {#                    </div>#}
                {#                </div>#}
                {##}
                {#                <div class="form-row field-is_active">#}
                {#                    <div class="checkbox-row">#}
                {#                        <input checked="checked" id="id_is_active" name="is_active" type="checkbox"/><label#}
                {#                            class="vCheckboxLabel" for="id_is_active">是否激活</label>#}
                {#                    </div>#}
                {#                </div>#}
                {#                <div class="form-row">#}
                {#                    <label name="comment">备注:</label>#}
                {#                    <input class="vTextField" type="text" name="comment">#}
                {#                </div>#}
                {#                <div class="submit-row">#}
                {#                    <button type="submit" class="btn">save</button>#}
                {#                    <button class="btn">cancle</button>#}
                {#                </div>#}
                {#            </fieldset>#}
                {#        </form>#}
                <!-- END Content -->
            </div>
        </div>
    </div>
{% endblock %}

nova/templates/config_file_editor.html
{% extends 'base.html' %}
{% block title %}配置文件{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-6 col-sm-8 col-md-12">
                <div class="col-md-offset-1 console-instance-head clearfix">
                    <div class="pull-left">
                        <h3><span>配置文件</span></h3>
                    </div>
                </div>

                <div class="col-md-offset-1 margin-top-1" id=toolbar>
                    <div style="font-family: Courier;font-weight: bold;">File: <span id="filename">{{ file }}</span>
                    </div>
            <textarea style="height: 40em;font-family: Courier;width: 100%;"
                      id=orig_content>{{ file_content }}</textarea>
            <textarea style="height: 40em;font-family: Courier;font-weight: bold;width: 100%;"
                      id=content>{{ file_content }}</textarea>
                    <button class="btn btn-primary" disabled="disabled" id="save" env="{{ env }}">保存</button>
                    <button class="btn btn-default" id="cancel" onclick="go_back()">取消</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            $("#orig_content").hide();
            var filename = $('#filename').text();
            var orig_content = $('#orig_content').val();
            $("#content").keydown(function (e) {
                if (e.keyCode) {
                    $("#save").attr("disabled", false)
                }
            });
            $('#save').click(function () {
                var content = $('#content').val();
                var env = $(this).attr('env');
                layer.confirm('是否确定保存?', {
                    icon: 3,
                    btn: ['确定', '取消'],
                    area: ['420px', '240px']
                }, function () {
                    $.ajax({
                        type: "POST",
                        url: "{% url 'save_config_file' %}",
                        data: JSON.stringify({
                            filename: filename,
                            orig_content: orig_content,
                            content: content,
                            env: env
                        }),
                        success: function (response) {
                            if (response['rtn'] == "00") {
                                layer.alert('保存成功！', {
                                    icon: 1,
                                    skin: 'layui-layer-molv',
                                    area: ['420px', '240px'],
                                    closeBtn: 0,
                                    end: function () {
                                        parent.location.reload();
                                    }
                                });
                            }
                            else {
                                layer.alert(response['msg'], {
                                    icon: 7,
                                    skin: 'layui-layer-molv',
                                    area: ['420px', '240px'],
                                    closeBtn: 0,
                                    end: function () {
                                        parent.location.reload();
                                    }
                                });
                            }
                        },
                        error: function (response) {
                            layer.alert(response, {
                                icon: 2,
                                skin: 'layui-layer-molv',
                                area: ['420px', '240px'],
                                closeBtn: 0
                            });
                        },
                        dataType: "json",
                        contentType: "application/json"
                    });
                });
            });
        });
        function go_back() {
            window.history.go(-1);
        }
    </script>
{% endblock %}

nova/templates/file_editor.html
{% load static %}
<!DOCTYPE>
<meta charset=utf-8>
<title>Text Editor</title>

<link href="{% static 'css/file_editor.css' %}" rel="stylesheet" type="text/css">
<script src="{% static 'js/file_editor.js' %}"></script>

<div id=toolbar>
    <button id=open>&#x1f4c2;</button>
    <button id=save>&#x1f4be;</button>
    <output id=name></output>
    <output id=type></output>
</div>
<textarea id=content></textarea>

nova/templates/index.html
{% extends 'base.html' %}

nova/templates/message.html
{% extends 'base.html' %}
{% block title %}消息{% endblock %}

{% block js %}
    <script>
        layer.alert('{{ msg|safe }}', {
            icon: 7,
            skin: 'layui-layer-molv' //墨绿风格
        });
        {#                //屏蔽浏览器滚动条#}
        {#                layer.open({#}
        {#                    content: '{{ msg|safe }}',#}
        {#                    scrollbar: false#}
        {#                });#}
    </script>
{% endblock %}

nova/templates/monitor_item.html
{% extends 'base.html' %}
{% load static %}
{% block title %}消息{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-6 col-sm-8 col-md-12">
                <div class="col-md-offset-1 console-instance-head clearfix">
                    <div class="pull-left">
                        <h3><span>监控</span></h3>
                    </div>
                </div>
                <span id="item_id" style="display: none">{{ item_id }}</span>
                <div class="col-md-offset-1" id="container" style="height:400px;"></div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    {#    <script src="https://img.hcharts.cn/highcharts/highcharts.js"></script>#}
    {#    <script src="https://cdn.hcharts.cn/highstock/highstock.js"></script>#}
    {#    <script src="https://img.hcharts.cn/highcharts/modules/exporting.js"></script>#}
    {#    <script src="https://img.hcharts.cn/highcharts-plugins/highcharts-zh_CN.js"></script>#}
    {#    <script src="{% static 'js/highcharts/highcharts.js' %}"></script>#}
    <script src="{% static 'js/highcharts/highstock.js' %}"></script>
    <script src="{% static 'js/highcharts/exporting.js' %}"></script>
    <script src="{% static 'js/highcharts/highcharts-zh_CN.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function requestData() {
            var item_id = document.getElementById("item_id").innerText;
            {#            alert(document.getElementById("item_id").innerText);#}
            $.ajax({
                url: "{% url 'http_data' %}?item_id=" + item_id,
                type: 'GET',
                success: function (data) {
                    if (typeof data == 'string') {
                        data = JSON.parse(data);
                    }
                    var last_time = data.last_time;
                    var item_name = data.item_name;
                    console.log(data);
                    data = data.data;
                    Highcharts.stockChart('container', {
                        chart: {
                            events: {
                                load: function () {
                                    var chart = $('#container').highcharts();
                                    var series = chart.series[0];
                                    setInterval(function () {
                                        $.ajax({
                                            url: "{% url 'http_data' %}?item_id=" + item_id + "&last_time=" + last_time,
                                            type: 'GET',
                                            success: function (res) {
                                                $.each(res.data, function (i, v) {
                                                    series.addPoint(v);
                                                });
                                            }
                                        });
                                    }, 60000);
                                }
                            }
                        },
                        credits: {
                            enabled: false,
                            text: "",
                            href: ""
                        },
                        rangeSelector: {
                            selected: 2
                        },
                        title: {
                            text: item_name
                        },
                        plotOptions: {
                            series: {
                                showInLegend: true
                            }
                        },
                        tooltip: {
                            split: false,
                            shared: true
                        },
                        series: [{
                            // type: 'line',
                            name: item_name,
                            data: data
                        }]
                    });
                },
                error: function (data) {
                    alert('ERROR');
                },
                dataType: "json",
                contentType: "application/json"
            });
        });
    </script>
{% endblock %}